In [2]:
import numpy as np
import pandas as pd
import sweetviz as sv

In [ ]:
student_record = pd.read_csv("F://Ml-Projects//Data//University//students_record_raw.csv")
report = sv.analyze(student_record)
report.show_html("F://Ml-Projects//University//Data_cleaning//Reports//raw_data_report.html" , open_browser=False)

In [4]:
df = student_record.copy()
df

,student_id,attendance_pct,mid_score,assignments_submitted,study_hours_per_week,lab_score,gpa,passed,student_email
0,96,NaN,21.1,3,14.0,9.6,1.88,0,s96@comsats.edu.pk
1,16,61.9,35.6,9,22.3,21.8,2.91,1,s16@comsats.edu.pk
2,31,61.2,20.7,9,11.6,21.9,3.03,1,s31@comsats.edu.pk
3,159,NaN,31.2,6,21.6,16.2,2.37,1,s159@comsats.edu.pk
4,129,73.8,34.2,9,14.8,20.2,3.12,1,s129@comsats.edu.pk
...,...,...,...,...,...,...,...,...,...
195,107,100.0,40.8,4,8.2,13.8,2.87,1,s107@comsats.edu.pk
196,15,41.0,24.8,4,13.3,21.5,2.33,1,s15@comsats.edu.pk
197,93,NaN,-5.0,7,19.1,16.4,2.16,1,s93@comsats.edu.pk
198,180,100.0,19.9,2,NaN,15.2,2.83,1,s180@comsats.edu.pk
199,103,NaN,35.5,9,15.9,21.1,2.67,1,s103@comsats.edu.pk

In [15]:
df.drop(columns=["student_id" , "student_email"] , inplace=True)

In [16]:
df["attendance_pct"] = df["attendance_pct"].fillna(df["attendance_pct"].median())
df["lab_score"] = df["lab_score"].fillna(df["lab_score"].median())
df["study_hours_per_week"] = df["study_hours_per_week"].fillna(df["study_hours_per_week"].median())

In [17]:
df.isnull().sum()

attendance_pct           0
mid_score                0
assignments_submitted    0
study_hours_per_week     0
lab_score                0
gpa                      0
passed                   0
dtype: int64

In [18]:
df = df[df["mid_score"] <= 50]

In [19]:
df

,attendance_pct,mid_score,assignments_submitted,study_hours_per_week,lab_score,gpa,passed
0,73.05,21.1,3,14.0,9.6,1.88,0
1,61.90,35.6,9,22.3,21.8,2.91,1
2,61.20,20.7,9,11.6,21.9,3.03,1
3,73.05,31.2,6,21.6,16.2,2.37,1
4,73.80,34.2,9,14.8,20.2,3.12,1
...,...,...,...,...,...,...,...
195,100.00,40.8,4,8.2,13.8,2.87,1
196,41.00,24.8,4,13.3,21.5,2.33,1
197,73.05,-5.0,7,19.1,16.4,2.16,1
198,100.00,19.9,2,13.0,15.2,2.83,1
199,73.05,35.5,9,15.9,21.1,2.67,1

In [ ]:
final_report = sv.analyze(df)
final_report.show_html("F://Ml-Projects//University//Data_cleaning//Reports//cleaned_data_report.html",open_browser=False)

In [21]:
df.to_csv("F://Ml-Projects//Data//University//cleaned_students_record.csv")