In [1]:
import numpy as np
import pandas as pd

In [2]:
titanic_test_df = pd.read_csv("F://Ml-Projects//Data//Titanic//test.csv")
df = titanic_test_df.copy()

In [3]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [4]:
df.drop(columns=["PassengerId" , "Name" , "Ticket" ] , inplace=True)

In [5]:
df.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0       3    male  34.5      0      0   7.8292   NaN        Q
1       3  female  47.0      1      0   7.0000   NaN        S
2       2    male  62.0      0      0   9.6875   NaN        Q
3       3    male  27.0      0      0   8.6625   NaN        S
4       3  female  22.0      1      1  12.2875   NaN        S

In [6]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
)

In [7]:
df["age"] = df["age"].fillna(df["age"].median())

In [9]:
df["has_cabin"] = df["cabin"].notna().astype(int)
df.drop(columns=["cabin"] , inplace=True)
df

     pclass     sex   age  sibsp  parch      fare embarked  has_cabin
0         3    male  34.5      0      0    7.8292        Q          0
1         3  female  47.0      1      0    7.0000        S          0
2         2    male  62.0      0      0    9.6875        Q          0
3         3    male  27.0      0      0    8.6625        S          0
4         3  female  22.0      1      1   12.2875        S          0
..      ...     ...   ...    ...    ...       ...      ...        ...
413       3    male  27.0      0      0    8.0500        S          0
414       1  female  39.0      0      0  108.9000        C          1
415       3    male  38.5      0      0    7.2500        S          0
416       3    male  27.0      0      0    8.0500        S          0
417       3    male  27.0      1      1   22.3583        C          0

[418 rows x 8 columns]

In [10]:
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])

In [11]:
df["fare"] = df["fare"].fillna(df["fare"].median())

In [12]:
df["sex"] = df["sex"].map({"female" : 0 , "male" : 1})

In [13]:
df = pd.get_dummies(data=df , columns=["embarked"] , drop_first=True)

In [14]:
df[["embarked_Q","embarked_S"]] = df[["embarked_Q","embarked_S"]].astype(int)

In [15]:
df

,pclass,sex,age,sibsp,parch,fare,has_cabin,embarked_Q,embarked_S
0,3,1,34.5,0,0,7.8292,0,1,0
1,3,0,47.0,1,0,7.0000,0,0,1
2,2,1,62.0,0,0,9.6875,0,1,0
3,3,1,27.0,0,0,8.6625,0,0,1
4,3,0,22.0,1,1,12.2875,0,0,1
...,...,...,...,...,...,...,...,...,...
413,3,1,27.0,0,0,8.0500,0,0,1
414,1,0,39.0,0,0,108.9000,1,0,0
415,3,1,38.5,0,0,7.2500,0,0,1
416,3,1,27.0,0,0,8.0500,0,0,1
417,3,1,27.0,1,1,22.3583,0,0,0

In [16]:
df.to_csv("F://Ml-Projects//Data//Titanic//cleaned_test_data.csv")